name: phd
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cartopy=0.21.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=1.2.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - geos=3.9.1
  - giflib=5.2.1
  - h5netcdf=1.2.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - ipykernel=6.15.0
  - ipython=8.13.2
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.2.1
  - libcxx=16.0.3
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.5.1
  - pooch=1.4.0
  - proj=8.2.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyaml=23.5.7
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.2
  - scikit-optimize=0.9.0
  - setuptools=66.0.0
  - shapely=2.0.1
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xarray=2023.6.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - adjusttext==1.0.4
      - colourmap==1.1.16
      - datazets==0.1.9
      - dill==0.3.7
      - ffmpeg-python==0.2.0
      - future==0.18.3
      - h5py==3.8.0
      - multiprocess==0.70.15
      - patsy==0.5.6
      - pca==2.0.5
      - scatterd==1.3.7
      - scipy==1.10.1
      - seaborn==0.13.1
      - statsmodels==0.14.1
